services:
  db:
    image: postgres:18.1-alpine3.23
    container_name: kyte-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kyte
    volumes:
      - db_data:/var/lib/postgresql/data

  seaweedfs:
    image: chrislusf/seaweedfs
    container_name: kyte-seaweedfs
    command: server -s3 -dir=/data
    ports:
      - "8333:8333"
      - "9333:9333"
    volumes:
      - seaweedfs_data:/data

volumes:
  db_data:
  seaweedfs_data: